FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /app

COPY *.csproj . 
RUN dotnet restore

COPY . .

WORKDIR /app
ENV ASPNETCORE_URLS=http://*:${PORT}
RUN dotnet publish -c Release -o out
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS runtime
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "WebHost.dll"]